package com.jj.game.boost.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.jj.game.boost.domain.DelayLostSave;

import com.jj.game.boost.dao.DelayLostSaveDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig delayLostSaveDaoConfig;

    private final DelayLostSaveDao delayLostSaveDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        delayLostSaveDaoConfig = daoConfigMap.get(DelayLostSaveDao.class).clone();
        delayLostSaveDaoConfig.initIdentityScope(type);

        delayLostSaveDao = new DelayLostSaveDao(delayLostSaveDaoConfig, this);

        registerDao(DelayLostSave.class, delayLostSaveDao);
    }
    
    public void clear() {
        delayLostSaveDaoConfig.clearIdentityScope();
    }

    public DelayLostSaveDao getDelayLostSaveDao() {
        return delayLostSaveDao;
    }

}
